services:

    app:
      image: best_insurance/api
      container_name: app

      depends_on:
        db:
          condition: service_started

      ports:
        - "8080:8080"
        - "5005:5005"

      environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/best_insurance
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Flavius10
          SPRING_JPA_HIBERNATE_DDL_AUTO: validate
          BPL_DEBUG_ENABLED: true
          BPL_DEBUG_SUSPEND: false
          BPL_DEBUG_PORT: 5005


      command: >
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx128m -Xms128m
        -jar /app/app.jar

    db:
      image: postgres:12.1-alpine
      container_name: db
      ports:
        - "5432:5432"

      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Flavius10
        POSTGRES_DB: best_insurance